1:
  hidden_dim: 64
  num_layers: 4
  data_dir: data_base/SOD_case1.h5
  stage1:
    epochs: 3000
    lr: 0.0001
    model_dir: results/case1/stage1
    scheduler: CosineAnnealingWarmRestarts
    scheduler_config:
      CosineAnnealingWarmRestarts:
        T_0: 1500 
        T_mult: 2
        eta_min: 0.000005
  stage2:
    epochs: 1000
    lr: 0.0001
    model_dir: results/case1/stage2
    scheduler: OneCycleLR
    N: 25
    scheduler_config:
      OneCycleLR:
        max_lr: 0.0005  
        pct_start: 0.3
        div_factor: 10
        final_div_factor: 100

2:
  hidden_dim: 64
  num_layers: 4
  data_dir: data_base/SOD_case2.h5
  stage1:
    epochs: 3000
    lr: 0.0001
    model_dir: results/case2/stage1
    scheduler: CosineAnnealingWarmRestarts
    scheduler_config:
      CosineAnnealingWarmRestarts:
        T_0: 1500 
        T_mult: 2
        eta_min: 0.000005
  stage2:
    epochs: 1000
    lr: 1.0e-5
    model_dir: results/case2/stage2
    N: 25
    TVD: True
    scheduler: OneCycleLR
    scheduler_config:
      OneCycleLR:
        max_lr: 1.0e-4 
        pct_start: 0.3
        div_factor: 10
        final_div_factor: 100