1:
  hidden_dim: 64
  num_layers: 4
  data_dir: data_base/SOD_case1.h5
  stage1: 
    epochs: 2000
    lr: 0.001
    model_dir: results/case1/stage1
    step_size: 100
    gamma: 0.5
  stage2: 
    epochs: 300
    lr: 0.0001
    model_dir: results/case1/stage2
    N: 25

2:
  hidden_dim: 64
  num_layers: 4
  data_dir: data_base/SOD_case2.h5
  stage1: 
    epochs: 2000
    lr: 0.001
    model_dir: results/case2/stage1
    step_size: 100
    gamma: 0.5
  stage2: 
    epochs: 300
    lr: 0.0001
    model_dir: results/case2/stage2
    N: 25