hidden_dim: 32
num_layers: 4
data_dir: data_base/cylinder_case.h5
stage1:
  epochs: 1000
  lr: 1.0e-3
  model_dir: results/stage1
  scheduler: CosineAnnealingWarmRestarts
  scheduler_config:
    CosineAnnealingWarmRestarts:
      T_0: 500 
      T_mult: 2
      eta_min: 5.01e-6
stage2:
  epochs: 1000
  lr: 1.0e-5
  model_dir: results/stage2
  N: 10
  scheduler: OneCycleLR
  scheduler_config:
    OneCycleLR:
      max_lr: 1.0e-4 
      pct_start: 0.3
      div_factor: 10
      final_div_factor: 100
